on:
  # schedule:
  #   - cron: '0 3 * * *' # run at 3 AM UTC

name: Nightly Release

jobs:
  nightly_release:
    name: Create nightly release
    if: ${{ github.repository_owner == 'input-output-hk' }}
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_nightly.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get version
        id: version
        run: |
          export VERSION=`cat ./jormungandr/Cargo.toml | grep "version" | head -n 1 | awk '{print $3}' | cut -d "\"" -f 2 `
          echo ::set-output name=version::$VERSION

      - name: Delete nightly with hub
        continue-on-error: true
        env:
          GITHUB_USER: ${{ secrets.GITHUB_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          bin/hub release delete nightly

      - name: Create Nightly
        id: create_nightly
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: nightly
          release_name: ${{ steps.version.outputs.version }}
          draft: false
          prerelease: true

  update_deps:
    name: Update dependencies
    if: ${{ github.repository_owner == 'input-output-hk' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - id: cargo-registry
        name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('Cargo.lock') }}

      - if: ${{ steps.cargo-registry.outputs.cache-hit != 'true' }}
        id: ls-crates-io-index
        name: Get head commit hash of crates.io registry index
        continue-on-error: true
        shell: bash
        run: |
          commit=$(
            git ls-remote --heads https://github.com/rust-lang/crates.io-index.git master |
            cut -f 1
          )
          echo "::set-output name=head::$commit"
      - if: ${{ steps.cargo-registry.outputs.cache-hit != 'true' }}
        name: Cache cargo registry index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry/index
          key: cargo-index-${{ steps.ls-crates-io-index.outputs.head }}
          restore-keys: |
            cargo-index-

      - if: ${{ steps.cargo-registry.outputs.cache-hit != 'true' }}
        name: Fetch dependencies
        run: cargo fetch --locked

      - if: ${{ steps.cargo-registry.outputs.cache-hit != 'true' }}
        name: Prune unpacked sources of dependency crates from cache
        shell: bash
        run: |
          rm -rf ~/.cargo/registry/src

  release_assets:
    name: Release assets
    if: ${{ github.repository_owner == 'input-output-hk' }}
    needs: [nightly_release, update_deps]
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          # Linux
          - {os: ubuntu-latest, target: x86_64-unknown-linux-gnu}
          # Macos
          - {os: macos-latest, target: x86_64-apple-darwin}
        target_cpu: [generic, broadwell]
        toolchain: [stable]
        cross: [false]
        include:
          # Windows
          - config: {os: windows-latest, target: x86_64-pc-windows-gnu}
            target_cpu: generic
            toolchain: stable-x86_64-pc-windows-gnu
            cross: false
          - config: {os: windows-latest, target: x86_64-pc-windows-gnu}
            target_cpu: broadwell
            toolchain: stable-x86_64-pc-windows-gnu
            cross: false
          - config: {os: windows-latest, target: x86_64-pc-windows-msvc}
            target_cpu: generic
            toolchain: stable-x86_64-pc-windows-msvc
            cross: false
          - config: {os: windows-latest, target: x86_64-pc-windows-msvc}
            target_cpu: broadwell
            toolchain: stable-x86_64-pc-windows-msvc
            cross: false
          # Cross targets
          - config: {os: ubuntu-latest, target: aarch64-unknown-linux-gnu}
            target_cpu: generic
            toolchain: stable
            cross: true
          - config: {os: ubuntu-latest, target: arm-unknown-linux-gnueabi}
            target_cpu: generic
            toolchain: stable
            cross: true
          - config: {os: ubuntu-latest, target: armv7-unknown-linux-gnueabihf}
            target_cpu: generic
            toolchain: stable
            cross: true
          - config: {os: ubuntu-latest,  target: x86_64-unknown-linux-musl}
            target_cpu: generic
            toolchain: stable
            cross: true
          - config: {os: ubuntu-latest,  target: x86_64-unknown-linux-musl}
            target_cpu: broadwell
            toolchain: stable
            cross: true
          - config: {os: ubuntu-latest, target: aarch64-linux-android}
            target_cpu: generic
            toolchain: stable
            cross: true
          # - config: {os: ubuntu-latest, target: mips64el-unknown-linux-gnuabi64}
          #   target_cpu: generic
          #   toolchain: stable
          #   cross: true
          # - config: {os: ubuntu-latest, target: powerpc64le-unknown-linux-gnu}
          #   target_cpu: generic
          #   toolchain: stable
          #   cross: true

    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          target: ${{ matrix.config.target }}
          override: true
          default: true

      - name: Get current date
        run: |
          export DATE=`date +'%Y%m%d'`;
          echo ::set-env name=DATE::$DATE
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Get version
        id: version
        run: |
          export VERSION=`cat ./jormungandr/Cargo.toml | grep "version" | head -n 1 | awk '{print $3}' | cut -d "\"" -f 2 `
          echo ::set-output name=version::$VERSION
        shell: bash

      # https://github.com/actions/runner/issues/498
      - if: ${{ runner.os == 'Windows' }}
        name: Fix up Cargo.lock hash
        shell: powershell
        run: |
          ((Get-Content Cargo.lock) -join "`n") + "`n" |
          Set-Content -NoNewline Cargo.lock

      # https://github.com/actions/virtual-environments/issues/895
      # https://github.com/actions/virtual-environments/issues/936
      - if: ${{ runner.os == 'Windows' }}
        name: Clean up cargo registry files
        run: rm -r -fo $env:UserProfile\.cargo\registry

      - name: Restore cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: cargo-registry-${{ hashFiles('Cargo.lock') }}

      - name: Create .cargo/config.toml
        shell: bash
        run: |
          mkdir .cargo
          cat > .cargo/config.toml <<EOF
          [target.${{ matrix.config.target }}]
          rustflags = ["-C", "target-cpu=${{ matrix.target_cpu }}", "-C", "lto"]
          EOF

      - name: Build jormungandr
        uses: actions-rs/cargo@v1
        env:
          DATE: ${{ env.DATE }}
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: |
            --manifest-path jormungandr/Cargo.toml
            --bin jormungandr
            --no-default-features
            --verbose
            --locked
            --release
            --target ${{ matrix.config.target }}

      - name: Build jcli
        uses: actions-rs/cargo@v1
        env:
          DATE: ${{ env.DATE }}
        with:
          use-cross: ${{ matrix.cross }}
          command: build
          args: |
            --manifest-path jcli/Cargo.toml
            --bin jcli
            --verbose
            --locked
            --release
            --target ${{ matrix.config.target }}

      - name: Pack binaries (Unix)
        if: matrix.config.os != 'windows-latest'
        run: |
          archive=jormungandr-${{ steps.version.outputs.version }}.${{ env.DATE }}-${{ matrix.config.target }}-${{ matrix.target_cpu }}.tar.gz
          tar -C ./target/${{ matrix.config.target }}/release -czvf $archive jormungandr jcli
          echo "::set-env name=RELEASE_ARCHIVE::$archive"
          echo "::set-env name=RELEASE_CONTENT_TYPE::application/gzip"

      - name: Pack binaries (Windows)
        if: matrix.config.os == 'windows-latest'
        run: |
          $archive = "jormungandr-${{ steps.version.outputs.version }}.${{ env.DATE }}-${{ matrix.config.target }}-${{ matrix.target_cpu }}.zip"
          $args = @{
            Path  = "./target/${{ matrix.config.target }}/release/jormungandr.exe",
                    "./target/${{ matrix.config.target }}/release/jcli.exe"
            DestinationPath = $archive
          }
          Compress-Archive @args
          echo "::set-env name=RELEASE_ARCHIVE::$archive"
          echo "::set-env name=RELEASE_CONTENT_TYPE::application/zip"

      - name: Upload binaries to nightly release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.nightly_release.outputs.upload_url }}
          asset_path: ./${{ env.RELEASE_ARCHIVE }}
          asset_name: ${{ env.RELEASE_ARCHIVE }}
          asset_content_type: ${{ env.RELEASE_CONTENT_TYPE }}
